language: node_js
node_js:
  - '10'
services:
  - postgresql
env:
  - NODE_ENV=test DATABASE_URL=postgres://postgres@localhost:5432/circles_test DATABASE_DIALECT=postgres
before_install:
  - psql -c 'create database circles_test;' -U postgres
install:
  - npm install
  - npm run db:migrate
  - npm run db:seed
script:
  - npm test
