name: run-tests
on: [push]
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: api
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Get circles-docker repository and copy configs
        uses: actions/checkout@v4
        with:
          repository: CirclesUBI/circles-docker.git
          ref: main
          path: circles-docker

      - name: Setup docker repo
        working-directory: circles-docker
        run: cp .env.example .env

      - name: Download and migrate contracts
        working-directory: circles-docker
        run: ./scripts/migrate-contracts.sh


      - name: Install dependencies
        run: npm ci
      - name: Setup env file
        run: cp .env.example .env

      - run: npm run db:migrate
      - run: npm run db:seed
      - run: npm run test
