name: run-tests
on: [push]
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: api
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4


      - name: Copy core configs
        run: cp .env.example .env

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Get circles-docker repository and copy configs
        uses: actions/checkout@v3
        with:
          repository: CirclesUBI/circles-docker.git
          ref: relayer-api-test
          path: circles-docker

      - name: Setup docker repo
        working-directory: circles-docker
        run: cp .env.example .env

      - name: Container setup via docker-compose only for ganache
        working-directory: circles-docker
        run: docker compose -f docker-compose.yml -f docker-compose.payment-api-pull.yml -p circles up --detach --remove-orphans --build ganache

      - name: Download and migrate contracts
        working-directory: circles-docker
        run: ./scripts/migrate-contracts.sh

      - name: Setup env file
        run: cp .env.example .env

      - name: Install dependencies
        run: npm ci

      - name: DB migrate
        run: npm run db:migrate

      - name: DB seed
        run: npm run db:seed

      - name: Run tests
        run: npm run test
