name: run-tests
on: [push]
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: api
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Read node version from .nvmrc
        id: nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '${{ steps.nvmrc.outputs.NODE_VERSION }}'

      - name: Install dependencies
        run: npm install
      - name: Setup env file
        run: cp .env.example .env
      - run: npm run db:migrate
      - run: npm run db:seed
      - run: npm test
