name: Build docker and upload to registry

on:
  push:
    tags:
      # strict semver regex
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-16.04
    steps:
      - name: Install dependencies
        run: |
          sudo snap install doctl
          sudo snap connect doctl:dot-docker

      - name: Configure auth for Digital Ocean
        env:
          CIRCLES_CI_DO_TOKEN: ${{ secrets.CIRCLES_CI_DO_TOKEN }}
        run: |
          doctl auth init -t ${CIRCLES_CI_DO_TOKEN}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          username: ${{ DOCKERHUB_USERNAME }}
          password: ${{ DOCKERHUB_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get ref
        id: parse_ref
        run: |
          echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

      - name: Digital Ocean Registry login
        run: |
          doctl registry login

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          IMAGE_VERSION: ${{ steps.parse_ref.outputs.tag }}
        with:
          context: .
          push: true
          tags: |
            registry.digitalocean.com/circles-registry/api:${IMAGE_VERSION}
            hub.docker.com/joincircles/circles-api:${IMAGE_VERSION}
